### ISSUE TITLE
Problems running the python run.py

### ISSUE THREAD

**Issue by ILoveGithub132** [mikavehns/BookGPT#10]
When I use my terminal to execute the command python run.py, this returns. I have tried fixing it myself, but nothing really seems to work. Maybe I'm just doing something wrong? Or maybe it's a bug I don't know. 

Does anyone know a fix to this problem?

Traceback (most recent call last): File "C:\Users\.....\BookGPT\src\run.py", line 3, in <module> from book import Book File "C:\Users\.....\BookGPT\src\book.py", line 1, in <module> import openai ModuleNotFoundError: No module named 'openai'

**Comment by VincenzoDon** [comment]
download from your terminal :
pip install openai

**Comment by VincenzoDon** [comment]
When the terminal say : No module named 'XXXXX'
You write in your terminal pip instal XXXXX

**Comment by SunilWarrier** [comment]
The best way is before running run.py please run the following in the src folder. That will install all the required libraries.
pip install -r requirements.txt

**Comment by mikavehns** [comment]
This error occurs when you don't install the required packages. Follow all setup instructions in the README,md file, to fix this error.
