### ISSUE TITLE
First book work, second fail (just title when I saved)

### ISSUE THREAD

**Issue by Lyesbcb** [mikavehns/BookGPT#4]
**Describe the bug**
I generated a first book and everything went well (12 chapters and 5000 words). When I tried to generate a second book, it runs for x time and after when it asks me to save I chose .md and it saves me only the title. I first thought of a credit problem but I did not exceed my quota at all.

**To Reproduce**
1. Generate first book
2. Try to generate a second book 

**Screenshots**
![image](https://user-images.githubusercontent.com/94790249/213442569-43ca48d3-355e-4312-872f-77fee5dfc10c.png)
![Uploading image.png…]()

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mikavehns** [comment]
I already noticed this error. Not quite sure why it occurs, but it seems like it is often when you skip the language. I will try to fix it in some of the next version, but thank you very much for the information.
