### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by noaether** [mikavehns/BookGPT#6]
**Describe the bug**
TypeError when loading selfimprovement.py

**To Reproduce**
1. Clone repository `git clone https://github.com/mikavehns/BookGPT.git`
2. Install requirements `pip install -r requirements.txt`
3. Run `python run.py`

**Expected behavior**
Interactive menu/CLI should appear.

**Severity**
Program does not work at all.

**Error Logs**
`Traceback (most recent call last):`
`  File "run.py", line 3, in <module>`
`    from book import Book`
`  File "/home/noa/Documents/BookGPT/src/book.py", line 3, in <module>`
`    from categories import *`
`  File "/home/noa/Documents/BookGPT/src/categories/__init__.py", line 1, in <module>`
`    from .selfimprovement import SelfImprovement`
`  File "/home/noa/Documents/BookGPT/src/categories/selfimprovement.py", line 6, in <module>`
`    class SelfImprovement:`
`  File "/home/noa/Documents/BookGPT/src/categories/selfimprovement.py", line 69, in SelfImprovement`
`    def get_structure(self, title: str, chapters: list[str]):`
`TypeError: 'type' object is not subscriptable`
![image](https://user-images.githubusercontent.com/67566122/213941152-1b8a1914-6198-4613-9cab-31f41a11ecc2.png)

**Desktop info**
 - OS: Zorin OS 16.2 x86_64 
 - Kernel: 5.15.0-46-generic
 - Python Version: Python 3.8.10

**Additional info**
Using python-is-python3, which means running `python run.py` actually runs `python3 run.py`. Ran the screenshot with python3 directly in case that module was at fault.

**Comment by malore350** [comment]
You should upgrade your python to >=3.9
