### ISSUE TITLE
Slight issue in documentation regarding how to install packages

### ISSUE THREAD

**Issue by ericgrosse** [mikavehns/BookGPT#7]
**Describe the bug**

`pip install -r requirements.txt` doesn't work if you are in the `BookGPT/src` folder, instead need to use `pip install -r ../requirements.txt` or a similar workaround (would installing from BookGPT root folder work? I'm not that familiar with python yet).

Not a big deal, but ensures beginners install their packages successfully in case they don't know what they're doing (such as non coders who want to take advantage of this repository).

**Comment by mikavehns** [comment]
I will change the README.md file. Thank you for informing me.
