### ISSUE TITLE
missing 'books'-folder

### ISSUE THREAD

**Issue by SimonB97** [mikavehns/BookGPT#8]
Title says it. I guess it should be in the 'BookGPT'-folder?

**Comment by malore350** [comment]
Do you mean that you couldn't clone the git, or you cannot find where your book is saved? If the latter, you will find it in `.../BookGPT/src/` folder

**Comment by mikavehns** [comment]
Changed it in the README file.

**Comment by SimonB97** [comment]
Thanks, I just found it. Expected it to be named by the title provided..
