### ISSUE TITLE
Installing requirements.txt

### ISSUE THREAD

**Issue by Stefan2ND** [mikavehns/BookGPT#9]
I get this error message every time I use the command " pip install -r requirements.txt " 

I might just be doing something wrong, but maybe some one smarter than me knows what I'm doing wrong :)

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by rowbot1** [comment]
I had some problem, the instructions say to run that command from the /src folder but the requirements.txt file is actually in the main folder. So go back to the main folder and run it again

**Comment by mikavehns** [comment]
Sorry for the mistake. I updated the README.md file.
